version: '3.7'

services:
  ts-node-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
    container_name: ts-node-docker
    expose:
      - '5000'
    ports:
      - '5000:5000'
    command: npm start
    environment:
      MONGODB_CONNECT: ${MONGODB_CONNECT}